# web server
PORT=8806
BODY_LIMIT="1M"
JWT_EXPIRE_TIME=1440

#database
DB_MASTER=["172.17.0.1:3306"]
DB_SLAVE=["172.17.0.1:3306"]
DB_NAME="horus"
DB_USER="root"
DB_PASS="123"
DB_ARGS="charset=utf8&collation=utf8_general_ci&parseTime=true&loc=Asia%2FHo_Chi_Minh"
DB_MAX_IDLE=2
DB_MAX_OPEN=4